platform :ios, '11.4'

use_frameworks!
inhibit_all_warnings!
workspace 'Utils'

def utils
  pod 'SwiftLint', '~> 0.30.1'
end

def common_pods 
	utils

	pod 'Device', '3.1.2'
  	pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift', :tag => '1.3.1'
end 

target 'Utils' do

  common_pods

  target 'UtilsTests' do
  	common_pods
  end

end
