# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def common_pods 
	pod 'Device', '3.1.2'
end 

target 'Utils' do
  use_frameworks!

  common_pods

  target 'UtilsTests' do
  	common_pods
  end

end
