platform :ios, '11.4'

use_frameworks!
inhibit_all_warnings!
workspace 'Utils'

def utils
  pod 'SwiftLint', '~> 0.30.1'
end

def common_pods 
	utils

  pod 'CryptoSwift', :git => 'https://github.com/krzyzanowskim/CryptoSwift', :tag => '1.4.0'
  pod 'Device', :path => '../Utils/Device', :tag => '3.3.0'
end 

target 'Utils' do

  common_pods

  target 'UtilsTests' do
    common_pods
  end

  target 'UtilsTestsHost' do
    common_pods
  end

end

### правка ворнингов, описанных здесь
### https://stackoverflow.com/questions/54704207/the-ios-simulator-deployment-targets-is-set-to-7-0-but-the-range-of-supported-d
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
