name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: |
        cd Utils
        gem install xcpretty -N
        make init
    - name: Force xcode 12
      run: |
        sudo xcode-select -switch /Applications/Xcode_12.4.app
    - name: Build
      run: |
        cd Utils
        make build
    - name: SPM Build
      run: |
        cd Utils
        make spm_build
    - name: Tests
      run: |
        cd Utils
        make test
