name: CI

# Controls when the action will run. 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited, synchronize ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2
    - name: Init
      run: |
        cd Utils
        make init
    - name: Force select xcode 13
      run: |
        sudo xcode-select -switch /Applications/Xcode_13.4.app
    - name: Build
      run: |
        cd Utils
        make build
    - name: SPM Build
      run: |
        cd Utils
        make spm_build
    - name: Tests
      run: |
        cd Utils
        make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.2.1
    - name: Pod Lib Lint
      run: |
        pod lib lint
